/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package battlestatepack;

/**
 *
 * @author Clara Currier
 */
public class Pathway {

    /*
     * A way to store paths generated by Pathway
     * Should be easy to move sprites along the generated lines
     */
    private int[] dirs;
    private float[] lengths;

    public Pathway(int turns) {
        dirs = new int[turns];
        lengths = new float[turns];
    }

    public Pathway(int dir, float length) {
        dirs = new int[1];
        dirs[0] = dir;
        lengths = new float[1];
        lengths[0] = length;
    }

    public void setDir(int index, int val) {
        dirs[index] = val;
    }

    public void setLength(int index, float val) {
        lengths[index] = val;
    }

    public int[] getDirs() {
        return dirs;
    }

    public float[] getLengths() {
        return lengths;
    }
}